export const foodItems = [
  "Club Turkey",
  "French Dip Roast Beef",
  "Cuban Pulled Pork",
  "Monte Cristo Ham",
  "Patty Melt Swiss",
  "Grilled Cheese Tomato Avocado",
  "Grilled Cheese Apple",
  "French Dip Fries",
  "French Dip Onion Rings",
  "French Bread Sausage Pizza",
  "Stromboli Pepperoni",
  "Calzone Ricotta",
  "Stuffed Shells Meat",
  "Stuffed Peppers Beef",
  "Stuffed Mushrooms Crab",
  "Stuffed Artichokes Lemon",
  "Breakfast Burrito Sausage",
  "Breakfast Tacos Bacon",
  "Breakfast Tacos Potato",
  "Breakfast Tacos Salsa",
  "California Burrito Shrimp",
  "California Burrito Veggie",
  "Street Tacos Al Pastor",
  "Street Tacos Carnitas",
  "Chili Cheese Dog Ketchup",
  "Corn Dog Mustard",
  "Funnel Cake Powdered Sugar",
  "Cheeseburger Onion Rings BBQ",
  "Cheeseburger Bacon Jalapeño",
  "Cheeseburger Avocado Swiss",
  "Cheeseburger Fried Egg Bacon",
  "Chocolate Chip Cookies (Soft)",
  "Chocolate Chip Cookies (Crispy)",
  "Oatmeal Raisin Cookies",
  "Peanut Butter Cookies",
  "Snickerdoodles",
  "Sugar Cookies",
  "Chocolate Cake",
  "Vanilla Cake",
  "Carrot Cake",
  "Red Velvet Cake",
  "New York-Style Cheesecake",
  "Strawberry Cheesecake",
  "Apple Crumble",
  "Peach Cobbler",
  "Blueberry Pie",
  "Cherry Pie",
  "Pecan Pie",
  "Pumpkin Pie",
  "Chocolate Fudge Brownies",
  "Blondie Brownies",
  "Seven Layer Bars",
  "Rice Krispie Treats",
  "Chocolate Chip Banana Bread",
  "Zucchini Bread",
  "Banana Muffins",
  "Blueberry Muffins",
  "Cornbread Muffins",
  "Chocolate Milkshake",
  "Strawberry Shortcake",
  "Brownie Sundae",
  "Caesar Salad (Chicken)",
  "BLT Salad",
  "Chicken Alfredo",
  "Fettuccine Alfredo",
  "Baked Ziti",
  "Cannoli",
  "Sfogliatelle",
  "Philly Soft Pretzel",
  "Crab Cakes",
  "Shrimp & Grits",
  "Chicken & Waffles",
  "Po' Boy",
  "Muffuletta",
  "Jambalaya (Andouille Sausage)",
  "Dirty Rice",
  "Beignets",
  "Club (Turkey)",
  "French Dip (Roast Beef)",
  "Cuban (Pulled Pork)",
  "Monte Cristo (Ham)",
  "Patty Melt",
  "Grilled Cheese (Tomato Avocado)",
  "Grilled Cheese (Apple)",
  "French Bread Pizza (Sausage)",
  "Stromboli",
  "Calzone",
  "Stuffed Shells",
  "Stuffed Peppers",
  "Stuffed Mushrooms",
  "Stuffed Artichokes",
  "Breakfast Burrito",
  "Breakfast Tacos",
  "California Burrito (Veggie)",
  "Street Tacos (Al Pastor)",
  "Chili Cheese Dog",
  "Corn Dog",
  "Funnel Cake",
  "Cheeseburger (Onion Rings BBQ)",
  "Cheeseburger (Bacon Jalapeño)",
  "Cheeseburger (Avocado Swiss)",
  "Cheeseburger (Fried Egg Bacon)",
  "Chocolate Chip Cookies",
  "Cheesecake (Strawberry)",
  "Banana Bread (Chocolate Chip)",
  "Jambalaya",
  "Club (Chicken)",
  "French Dip (French Fries)",
  "Cuban Sandwich",
  "Philly Cheesesteak",
  "Grilled Cheese (Tomato)",
  "Grilled Cheese (Tomato Soup)",
  "French Bread Pizza",
  "Calzone (Vegetarian)",
  "Stuffed Shells (Ricotta)",
  "Stuffed Peppers (Green)",
  "Stuffed Mushrooms (Cremini)",
  "Breakfast Burrito (Bacon)",
  "Breakfast Tacos (Scrambled Eggs)",
  "Street Tacos (Carnitas Avocado)",
  "Chili Cheese Dog (Ketchup Mustard)",
  "Corn Dog (Ketchup)",
  "Funnel Cake (Strawberries)",
  "Cheeseburger (Bacon)",
  "Cheeseburger (Jalapeño)",
  "Cheeseburger (Swiss)",
  "Chocolate Chip Cookies (Milk Chocolate)",
  "Oatmeal Raisin Cookies (Spiced)",
  "Peanut Butter & Jelly Sandwich",
  "Sugar Cookies (Vanilla)",
  "Carrot Cake (Cream Cheese Frosting)",
  "Red Velvet Cake (Cream Cheese Frosting)",
  "Apple Crisp (Oatmeal Topping)",
  "Peach Cobbler (Vanilla Ice Cream)",
  "Blueberry Pie (Lattice Crust)",
  "Cherry Pie (Double Crust)",
  "Pecan Pie (Gingersnap Crust)",
  "Pumpkin Pie (Whipped Cream)",
  "Chocolate Chip Brownie",
  "Seven Layer Bar (Coconut)",
  "Rice Krispie Treats (Marshmallow)",
  "Banana Bread",
  "Zucchini Bread (Lemon)",
  "Blueberry Muffin",
  "Cornbread",
  "Chocolate Shake",
  "Strawberry Sundae",
  "Caesar Salad",
  "Chicken Caesar Salad (Dressing)",
  "BLT Salad (Avocado)",
  "Chicken Fettuccine Alfredo",
  "Baked Ziti (Meat Sauce)",
  "Sfogliatelle (Ricotta)",
  "Crab Cakes (Remoulade Sauce)",
  "Chicken and Waffles (Syrup)",
  "Po' Boy (Shrimp)",
  "Jambalaya (Chicken)",
  "Beignets (Powdered Sugar)",
  "Rueben Sandwich (Sauerkraut)",
  "Lobster Mac & Cheese (Truffle Oil)",
  "Eggplant Parmesan (Marinara)",
  "Chicken Marsala (Mushrooms)",
  "Chicken Piccata (Lemon Caper)",
  "Chicken Tetrazzini (Mushrooms Peas)",
  "Lobster Mac & Cheese",
  "Chicken Parmigiana",
  "Eggplant Parmesan",
  "Chicken Marsala",
  "Veal Marsala",
  "Chicken Piccata",
  "Chicken Florentine",
  "Rueben Fritters",
  "Chicken Tetrazzini",
  "Chicken Divan",
  "Chicken Pot Pie Casserole",
  "Tuna Noodle Casserole",
  "Shepherd's Pie",
  "Chicken Fried Steak (Gravy)",
  "Chicken Fried Chicken",
  "Chicken & Dumplings",
  "Chicken Marbella",
  "Chicken Kiev",
  "Chicken Cacciatore",
  "Chicken Tortilla Soup",
  "Chicken Tortilla Salad",
  "Chicken Fajita Salad",
  "Southwest Chicken Salad",
  "Snickerdoodle Cookies",
  "Cheesecake (New York-style)",
  "Chicken Pot Pie",
  "Chili Cheese Fries",
  "Jumbo Shrimp Cocktail",
  "Club Salad with Grilled Chicken",
  "Philly Cheesesteak Hoagie",
  "French Onion Soup",
  "Cream of Broccoli Soup",
  "Chicken Caesar Salad",
  "Shrimp and Grits",
  "Chicken and Waffles",
  "Po' Boy Sandwich",
  "Muffuletta Sandwich",
  "Jambalaya with Andouille Sausage",
  "Lobster Mac and Cheese",
  "Shepherds Pie",
  "Chicken Fried Steak with Gravy",
  "Chicken and Dumplings",
  "Hamburger",
  "Cheeseburger",
  "Pizza (various styles)",
  "French Fries",
  "Mashed Potatoes",
  "Mac and Cheese",
  "Fried Chicken",
  "BBQ Ribs",
  "Steak",
  "Apple Pie",
  "Hot Dogs",
  "Grilled Cheese",
  "Tacos",
  "Burritos",
  "Nachos",
  "Chicken Wings",
  "Corn on the Cob",
  "Chili",
  "Seafood Gumbo",
  "Pulled Pork Sandwich",
  "Biscuits and Gravy",
  "Grits",
  "Cobb Salad",
  "California Roll",
  "Reuben Sandwich",
  "Lobster Roll",
  "Clamb Chowder",
  "Boston Baked Beans",
  "Key Lime Pie",
  "Chicago Deep Dish Pizza",
  "New York-Style Pizza",
  "Detroit-Style Pizza",
  "Fajitas",
  "Quesadilla",
  "Pancakes",
  "Waffles",
  "French Toast",
  "Hash Browns",
  "Scrambled Eggs",
  "Bacon",
  "Sausages",
  "Oatmeal",
  "Bagel with Cream Cheese",
  "Donut",
  "Cupcake",
  "Brownies",
  "Ice Cream",
  "Cheesecake",
  "Apple Crisp",
  "Peanut Butter and Jelly Sandwich",
  "Tuna Salad Sandwich",
  "Club Sandwich",
  "BLT Sandwich",
  "Grilled Chicken Sandwich",
  "Beef Stew",
  "Chicken Noodle Soup",
  "Tomato Soup and Grilled Cheese",
  "Pot Roast",
  "Meatloaf",
  "Lasagna",
  "Spaghetti and Meatballs",
  "Stir-Fry",
  "California Burrito",
  "Street Tacos",
  "Al Pastor",
  "Carnitas",
  "Spicy Tuna Roll",
  "Tempura",
  "Pad Thai",
  "General Tso's Chicken",
  "Kung Pao Chicken",
  "Egg Foo Young",
  "Fortune Cookies",
  "Falafel",
  "Hummus",
  "Gyro",
  "Souvlaki",
  "Buffalo Wings",
  "Onion Rings",
  "Tater Tots",
  "Chicken Tenders",
  "Milkshake",
  "Root Beer Float",
  "Sweet Potato Fries",
  "Guacamole",
  "Chips and Salsa",
  "Chicken Fried Steak",
  "Spaghetti",
  "Fried fish",
  "Kefir",
  "Yogurt salad",
  "Chicken curry",
  "Pizza Margherita",
  "Stir-fry",
  "Chocolate chip cookies",
  "Roast chicken",
  "Pasta carbonara",
  "Sushi",
  "Shepherd's pie",
  "Beef stew",
  "Caesar salad",
  "Fish and chips",
  "Bangers and mash",
  "Corned beef and cabbage",
  "Beef Wellington",
  "Bread pudding",
  "Cottage pie",
  "Chicken Parmesan",
  "Veal Parmesan",
  "Beef stroganoff",
  "Chicken piccata",
  "Pork tenderloin",
  "Beef brisket",
  "Pulled pork",
  "Beef bourguignon",
  "Chicken tikka masala",
  "Butter chicken",
  "Tandoori chicken",
  "Massaman curry",
  "Tom yum soup",
  "Kung Pao chicken",
  "Sweet and sour chicken",
  "Moo shu pork",
  "General Tso's chicken",
  "Beef and broccoli",
  "Szechuan beef",
  "Shrimp fried rice",
  "Vegetable fried rice",
  "Beef chow mein",
  "Chicken chow mein",
  "Shrimp lo mein",
  "Beef teriyaki",
  "Chicken teriyaki",
  "Salmon teriyaki",
  "Shrimp teriyaki",
  "Vegetable tempura",
  "Shrimp tempura",
  "Chicken katsu",
  "Tonkatsu",
  "Gyudon",
  "Sushi rolls",
  "California roll",
  "Philadelphia roll",
  "Spicy tuna roll",
  "Dragon roll",
  "Rainbow roll",
  "Cucumber roll",
  "Avocado roll",
  "Salmon roll",
  "Tuna roll",
  "Shrimp tempura roll",
  "Spider roll",
  "Eel roll",
  "Alaska roll",
  "Volcano roll",
  "Texas roll",
  "Bagel and lox",
  "Eggs Benedict",
  "Biscuits and gravy",
  "Chicken and waffles",
  "French toast",
  "Belgian waffles",
  "Crepe",
  "Omelette",
  "Quiche",
  "Frittata",
  "Eggs Florentine",
  "Eggs Sardou",
  "Shakshuka",
  "Scrambled eggs",
  "Hard-boiled eggs",
  "Deviled eggs",
  "Egg salad",
  "Tuna salad",
  "Chicken salad",
  "Cobb salad",
  "Waldorf salad",
  "Greek salad",
  "Nicoise salad",
  "Caprese salad",
  "Fruit salad",
  "Coleslaw",
  "Macaroni salad",
  "Potato salad",
  "Pasta salad",
  "Ambrosia salad",
  "Broccoli salad",
  "Spinach salad",
  "Wedge salad",
  "Antipasto salad",
  "Chef salad",
  "House salad",
  "Mashed potatoes",
  "French fries",
  "Grilled cheese sandwich",
  "Tomato soup",
  "Apple pie",
  "Banana bread",
  "Risotto",
  "Beef tacos",
  "Chicken parmesan",
  "Beef stir-fry",
  "Vegetable stir-fry",
  "Beef burritos",
  "Cesar salad",
  "Chicken soup",
  "Clam chowder",
  "Minestrone soup",
  "French onion soup",
  "Lentil soup",
  "Potato soup",
  "Split pea soup",
  "Chili con carne",
  "Vegetable curry",
  "Beef curry",
  "Vegetable lasagna",
  "Cheese pizza",
  "Pepperoni pizza",
  "Vegetable pizza",
  "BBQ chicken pizza",
  "Margherita pizza",
  "Hawaiian pizza",
  "Meat lovers pizza",
  "Seafood pizza",
  "Pesto pasta",
  "Alfredo pasta",
  "Macaroni and cheese",
  "Linguine with clam sauce",
  "Carbonara pasta",
  "Shrimp scampi",
  "Spaghetti aglio e olio",
  "Fettuccine alfredo",
  "Tiramisu",
  "Chocolate cake",
  "Ice cream",
  "Apple crisp",
  "Key lime pie",
  "Pumpkin pie",
  "Blueberry muffins",
  "Ratatouille",
  "Bolognese sauce",
  "Bechamel sauce",
  "Hollandaise sauce",
  "Marinara sauce",
  "Pesto sauce",
  "Salsa",
  "Pesto",
  "Tapenade",
  "Bruschetta",
  "Antipasto",
  "Stuffed peppers",
  "Eggplant parmesan",
  "Chicken fajitas",
  "Fish tacos",
  "Teriyaki chicken",
  "Miso soup",
  "Ceviche",
  "Gazpacho",
  "Quiche Lorraine",
  "Steak Diane",
  "Lobster bisque",
  "Crab cakes",
  "Escargot",
  "Bouillabaisse",
  "Coq au vin",
  "Croque monsieur",
  "Crepes Suzette",
  "Moussaka",
  "Baba ganoush",
  "Tabbouleh",
  "Shawarma",
  "Baklava",
  "Spanakopita",
  "Dolma",
  "Gyoza",
  "Ramen",
  "Pho",
  "Pad see ew",
  "Banh mi",
  "Bibimbap",
  "Kimchi",
  "Bulgogi",
  "Dumplings",
  "Samosa",
  "Naan",
  "Tikka masala",
  "Palak paneer",
  "Chana masala",
  "Biryani",
  "Dosa",
  "Idli",
  "Vada",
  "Tandoori naan",
  "Malai kofta",
  "Paneer tikka",
  "Aloo gobi",
  "Raita",
  "Pakora",
  "Jalebi",
  "Chole bhature",
  "Pani puri",
  "Samosa chaat",
  "Aloo tikki",
  "Matar paneer",
  "Bhindi masala",
  "Korma",
  "Kofta curry",
  "Aloo paratha",
  "Chapati",
  "Puri",
  "Upma",
  "Medu vada",
  "Rava dosa",
  "Hyderabadi biryani",
  "Chicken biryani",
  "Goan fish curry",
  "Vindaloo",
  "Mulligatawny soup",
  "Sheer khurma",
  "Halwa",
  "Rasmalai",
  "Gulab jamun",
  "Rasgulla",
  "Ladoo",
  "Kheer",
  "Barfi",
  "Shrikhand",
  "Pav bhaji",
  "Vada pav",
  "Dabeli",
  "Misal pav",
  "Poha",
  "Thalipeeth",
  "Sabudana khichdi",
  "Puran poli",
  "Modak",
  "Dhokla",
  "Khandvi",
  "Khaman",
  "Undhiyu",
  "Handvo",
  "Gujarati kadhi",
  "Thepla",
  "Methi na gota",
  "Chakri",
  "Khakhra",
  "Ghughra",
  "Fafda",
  "Kachori",
  "Gathiya",
  "Sev",
  "Kachumber",
  "Aloo chaat",
  "Papdi chaat",
  "Bhel puri",
  "Dahi puri",
  "Panipuri",
  "Ragda pattice",
  "Sev puri",
  "Katori chaat",
  "Tuna sandwich",
  "Club sandwich",
  "Turkey sandwich",
  "BLT sandwich",
  "Grilled chicken sandwich",
  "Roast beef sandwich",
  "Pulled pork sandwich",
  "Ham and cheese sandwich",
  "Reuben sandwich",
  "Monte Cristo sandwich",
  "Chicken Caesar salad",
  "Chef's salad",
  "Mozzarella sticks",
  "Onion rings",
  "Fried calamari",
  "Buffalo wings",
  "Chicken tenders",
  "Cheese fries",
  "Potato skins",
  "Garlic bread",
  "Stuffed mushrooms",
  "Chicken wings",
  "Quesadillas",
  "Spinach dip",
  "Fried pickles",
  "Cheese platter",
  "Crudites",
  "Fruit platter",
  "Charcuterie board",
  "Bacon cheeseburger",
  "Double cheeseburger",
  "Veggie burger",
  "Turkey burger",
  "BBQ burger",
  "Mushroom Swiss burger",
  "California burger",
  "Pulled pork burger",
  "Fish burger",
  "Tuna melt sandwich",
  "Philly cheesesteak",
  "French dip sandwich",
  "Meatball sub",
  "Grilled ham and cheese",
  "Sloppy joe sandwich",
  "Cuban sandwich",
  "Bahn mi sandwich",
  "Turkey club sandwich",
  "Ham and Swiss sandwich",
  "Pastrami sandwich",
  "Roast beef and cheddar sandwich",
  "Chicken parm sandwich",
  "Buffalo chicken sandwich",
  "BBQ pulled pork sandwich",
  "Egg salad sandwich",
  "Turkey cranberry sandwich",
  "Peanut butter and jelly sandwich",
  "Grilled peanut butter and banana sandwich",
  "Grilled chicken wrap",
  "Caesar chicken wrap",
  "Buffalo chicken wrap",
  "Crispy chicken wrap",
  "BLT wrap",
  "Turkey club wrap",
  "Veggie wrap",
  "Greek chicken wrap",
  "Hummus and veggie wrap",
  "Tuna salad wrap",
  "Grilled vegetable wrap",
  "Chicken Caesar wrap",
  "Southwest chicken wrap",
  "Cobb salad wrap",
  "Buffalo chicken salad wrap",
  "Chicken fajita wrap",
  "California turkey wrap",
  "Turkey cranberry wrap",
  "Chicken gyro",
  "Beef kebab",
  "Lamb tagine",
  "Salmon en papillote",
  "Lobster mac and cheese",
  "Mushroom risotto",
  "Avocado toast",
  "Tofu stir-fry",
  "Black bean quesadillas",
  "Spinach and feta stuffed chicken breast",
  "Shrimp scampi pasta",
  "Teriyaki salmon",
  "Cauliflower pizza crust",
  "Greek yogurt parfait",
  "Zucchini noodles with pesto",
  "Quinoa salad with roasted vegetables",
  "Caprese salad skewers",
  "Spinach and ricotta stuffed shells",
  "BBQ pulled jackfruit sandwich",
  "Coconut curry tofu",
  "Soba noodle salad",
  "Falafel wrap",
  "Veggie sushi rolls",
  "Lentil shepherd's pie",
  "Stuffed portobello mushrooms",
  "Buffalo cauliflower bites",
  "Thai green curry",
  "Spinach and artichoke stuffed mushrooms",
  "Teriyaki tofu bowls",
  "Quinoa stuffed bell peppers",
  "Mushroom barley soup",
  "Eggplant roll-ups",
  "Black bean burgers",
  "Stuffed acorn squash",
  "Lentil walnut loaf",
  "Veggie stir-fry with cashews",
  "Sweet potato black bean enchiladas",
  "Cauliflower rice pilaf",
  "Chickpea curry",
  "Pumpkin gnocchi",
  "Roasted vegetable frittata",
  "Beet and goat cheese salad",
  "Coconut lentil curry",
  "Cucumber avocado gazpacho",
  "Quinoa tabbouleh salad",
  "Stuffed grape leaves",
  "Roasted Brussels sprouts with balsamic glaze",
  "Mushroom Wellington",
  "Ratatouille tart",
  "Cauliflower buffalo wings",
  "Lentil sloppy joes",
  "Zucchini boats filled with quinoa",
  "Black bean and corn salad",
  "Greek lentil salad",
  "Spinach and ricotta stuffed portobello mushrooms",
  "Avocado chickpea salad",
  "Tofu scramble",
  "Eggplant caprese stacks",
  "Mediterranean quinoa salad",
  "Sweet potato toast",
  "Cauliflower alfredo",
  "Quinoa stuffed zucchini",
  "Chickpea avocado wrap",
  "Tempeh stir-fry",
  "Butternut squash risotto",
  "Eggplant parmesan stacks",
  "Tofu banh mi",
  "Mushroom lentil meatballs",
  "Coconut curry lentils",
  "Portobello mushroom steaks",
  "Avocado cucumber sushi",
  "Lentil walnut tacos",
  "Veggie spring rolls",
  "Roasted vegetable couscous",
  "Quinoa avocado salad",
  "Stuffed sweet potatoes",
  "Black bean corn enchiladas",
  "Teriyaki tempeh bowls",
  "Cauliflower tikka masala",
  "Spinach and feta stuffed peppers",
  "Chickpea spinach curry",
  "Zucchini noodle pad Thai",
  "Buffalo cauliflower salad",
  "Sesame tofu stir-fry",
  "Stuffed bell pepper soup",
  "Mediterranean stuffed eggplant",
  "Cauliflower potato mash",
  "Vegan sushi burrito",
  "Quinoa black bean chili",
  "Sweet potato black bean tacos",
  "Lentil spinach curry",
  "Mushroom lentil shepherd's pie",
  "Eggplant parmesan pasta",
  "Tofu tikka masala",
  "Cauliflower chickpea curry",
  "Veggie stir-fry with peanut sauce",
  "Lentil mushroom bolognese",
  "Spaghetti squash primavera",
  "Vegan mac and cheese",
  "Roasted vegetable quinoa bowl",
  "Chickpea avocado salad",
  "Sweet potato chickpea curry",
  "Stuffed acorn squash with quinoa",
  "Cauliflower buffalo wraps",
  "Vegan shepherd's pie",
  "Portobello mushroom burgers with avocado",
  "Quinoa black bean burgers",
  "Tofu vegetable stir-fry",
  "Veggie sushi bowl",
  "Coconut curry vegetables",
  "Stuffed portobello mushrooms with quinoa",
  "Sweet potato black bean burritos",
  "Lentil vegetable curry",
  "Mushroom lentil loaf",
  "Vegan stuffed peppers",
  "Cauliflower rice stir-fry",
  "Tofu noodle soup",
  "Vegan taco salad",
  "Chickpea avocado wraps",
  "Sweet potato chickpea stew",
  "Stuffed butternut squash",
  "Cauliflower rice sushi",
  "Vegan lentil soup",
  "Portobello mushroom fajitas",
  "Quinoa avocado bowls",
  "Tofu lettuce wraps",
  "Veggie quinoa stir-fry",
  "Coconut curry noodles",
  "Stuffed cabbage rolls",
  "Sweet potato black bean chili",
  "Lentil curry soup",
  "Mushroom walnut burgers",
  "Vegan paella",
  "Cauliflower rice burrito bowls",
  "Tofu vegetable curry",
  "Veggie sushi rolls with avocado",
  "Coconut curry lentil soup",
  "Stuffed spaghetti squash boats",
  "Vegan stuffed mushrooms",
  "Cauliflower rice sushi rolls",
  "Tofu pad Thai",
  "Veggie stir-fry with tofu",
  "Coconut curry chickpeas",
  "Stuffed bell peppers with quinoa",
  "Cauliflower pizza with vegan cheese",

  "Sashimi",
  "Nigiri",
  "Maki Roll",
  "Udon",
  "Soba",
  "Green Curry",
  "Massaman Curry",
  "Tom Yum Soup",
  "Spring Rolls",
  "Dumplings (Pork)",
  "Dumplings (Vegetable)",
  "Wontons",
  "Sweet and Sour Pork",
  "Peking Duck",
  "Mapo Tofu",
  "Kimchi Fried Rice",
  "Tandoori Chicken",
  "Butter Chicken",
  "Palak Paneer",
  "Baba Ganoush",
  "Gyros",
  "Fish and Chips",
  "Bangers and Mash",
  "Shepherd's Pie (Ground Lamb)",
  "Cottage Pie (Ground Beef)",
  "Steak and Kidney Pie",
  "Toad in the Hole (Sausages)",
  "Full English Breakfast",
  "Scotch Eggs",
  "Chicken Tikka Masala",
  "Saag Paneer",
  "Aloo Gobi",
  "Banh Mi",
  "Bun Bo Hue",
  "Bun Cha",
  "Kimchi Jjigae",
  "Bulgogi Stew",
  "Bibim Guksu",
  "Tom Kha Gai",
  "Massaman Curry (Beef)",
  "Green Curry (Seafood)",
  "Paella", // Spanish
  "Gazpacho", // Spanish
  "Tortilla Española", // Spanish
  "Ratatouille", // French
  "Quiche Lorraine", // French
  "Crêpes", // French
  "Lasagna (Meat)", // Italian
  "Lasagna (Vegetarian)", // Italian
  "Risotto", // Italian
  "Tiramisu", // Italian
  "Gelato", // Italian
  "Schnitzel", // Austrian
  "Sauerbraten", // German
  "Bratwurst", // German
  "Pretzel", // German
  "Goulash", // Hungarian
  "Paprikash", // Hungarian
  "Pierogi", // Polish
  "Borscht", // Eastern European
  "Pelmeni", // Russian
  "Stroganoff", // Russian
  "Dolmades", // Greek
  "Moussaka (Vegetarian)", // Greek
  "Falafel Wrap", // Middle Eastern
  "Shawarma Plate", // Middle Eastern
  "Baba Ganoush with Pita", // Middle Eastern
  "Tabbouleh", // Middle Eastern
  "Falafel Pita", // Middle Eastern
  "Tacos al Pastor", // Mexican
  "Carnitas Tacos", // Mexican
  "Cochinita Pibil", // Mexican
  "Mole Poblano", // Mexican
  "Guacamole Salad", // Mexican
  "Ceviche", // Peruvian
  "Lomo Saltado", // Peruvian
  "Aji de Gallina", // Peruvian
  "Arroz con Pollo", // Latin American
  "Feijoada", // Brazilian
  "Brigadeiros", // Brazilian
  "Empanadas", // Argentinian
  "Dulce de Leche", // Argentinian
  "Kimchi Pancake", // Korean
  "Japchae", // Korean
  "Bibimbap (Dolsot)", // Korean
  "Tteokbokki", // Korean
  "Tom Yum Goong (Shrimp)", // Thai
  "Green Curry (Chicken)", // Thai
  "Pad See Ew", // Thai
  "Mango Sticky Rice", // Thai
  "Bun Bo Hue (Beef)", // Vietnamese
  "Bun Cha (Grilled Pork)", // Vietnamese
  "Pho (Chicken)", // Vietnamese
  "Com Tam", // Vietnamese
  "Spring Rolls (Vegetable)", // Vietnamese
  "Spring Rolls (Shrimp)", // Vietnamese
  "Dosas", // Indian
  "Idli", // Indian
  "Vada", // Indian
  "Butter Chicken Curry", // Indian
  "Samosas", // Indian
  "Rogan Josh", // Indian
  "Biryani", // Indian
  "Sushi (Salmon)", // Japanese
  "Sushi (Tuna)", // Japanese
  "Edamame", // Japanese
  "Tempura (Vegetable)", // Japanese
  "Tempura (Shrimp)", // Japanese
  "Yakitori", // Japanese
  "Okonomiyaki", // Japanese
  "Takoyaki", // Japanese
  "Dalgona Coffee", // Korean
  "Bulgogi Bowl", // Korean
  "Kimchi Stew (Soft Tofu)", // Korean
  "Sundubu Jjigae", // Korean
  "Bibimbap (Gochujang Sauce)", // Korean
  "Jajangmyeon", // Korean
  "Tteokbokki (Fish Cake)", // Korean
  "Hot Pot", // Chinese (shared dish)
  "Kung Pao Beef", // Chinese
  "Mapo Tofu (Pork)", // Chinese
  "Dan Dan Noodles", // Chinese
  "Xiao Long Bao", // Chinese
  "Dumplings (Soup)", // Chinese
  "Wontons (Soup)", // Chinese
  "Char Siu Bao", // Chinese
  "Egg Drop Soup", // Chinese
  "Wonton Soup", // Chinese
  "Hot and Sour Soup", // Chinese
  "Kung Pao Shrimp", // Chinese
  "Moo Shu Pork", // Chinese
  "Peking Duck Pancakes", // Chinese
  "Scallion Pancakes", // Chinese
  "Spring Rolls (Chicken)", // Chinese
  "Spring Rolls (Duck)", // Chinese
  "Nasi Goreng", // Indonesian
  "Mie Goreng", // Indonesian
  "Rendang", // Indonesian
  "Gado-Gado", // Indonesian
  "Satay", // Indonesian
  "Tom Kha Kai (Chicken)", // Thai
  "Pad Kee Mao", // Thai
  "Gaeng Kaeng Curry", // Thai
  "Mango with Sticky Rice (Coconut Milk)", // Thai
  "Bun Bo Hue (Pork)", // Vietnamese
  "Bun Cha (Nem)", // Vietnamese (Nem refers to spring rolls)
  "Pho (Vegetarian)", // Vietnamese
  "Banh Xeo", // Vietnamese
  "Goi Cuon", // Vietnamese (Spring rolls)
  "Bun Rieu", // Vietnamese (Noodle soup)
  "Bahn Mi (Tofu)", // Vietnamese
  "Bahn Mi (Chicken)", // Vietnamese
  "Falafel Bowl", // Middle Eastern
  "Hummus Wrap", // Middle Eastern
  "Baba Ganoush Platter", // Middle Eastern
  "Tabbouleh Salad", // Middle Eastern
  "Ethiopian Beef Stew (Shiro Wat)", // Ethiopian
  "Doro Wat (Spicy Chicken Stew)", // Ethiopian
  "Injera (Flatbread)", // Ethiopian
  "Ful Medames (Fava Beans)", // Egyptian
  "Koshari (Lentil Dish)", // Egyptian
  "Moussaka (Lentil)", // Egyptian
  "Menemen (Eggs with Vegetables)", // Turkish
  "Iskender Kebab", // Turkish
  "Dolma (Grape Leaves)", // Turkish
  "Baklava (Pistachio)", // Turkish
  "Lokma (Fried Dough Balls)", // Turkish
  "Paella Valenciana (Chicken & Seafood)", // Spanish
  "Gambas al Ajillo (Garlic Shrimp)", // Spanish
  "Patatas Bravas (Spicy Potatoes)", // Spanish
  "Tortilla de Patatas (Spanish Omelette)", // Spanish
  "Coq au Vin (Chicken in Wine)", // French
  "Bouillabaisse (Seafood Stew)", // French
  "Ratatouille (Provençal)", // French
  "Crêpes Suzette (Dessert Crêpes)", // French
  "Cannelloni (Pasta Dish)", // Italian
  "Pesto Pasta", // Italian
  "Minestrone Soup", // Italian
  "Panna Cotta (Dessert)", // Italian
  "Apple Strudel", // Austrian
  "Käsespätzle (Cheese Spaetzle)", // Austrian
  "Sauerbraten with Potato Dumplings", // German
  "Kartoffelpuffer (Potato Pancakes)", // German
  "Pörkölt (Hungarian Stew)", // Hungarian
  "Chicken Paprikash", // Hungarian
  "Zapiekanka (Polish Pizza)", // Polish
  "Kielbasa (Sausage)", // Polish
  "Blintzes (Sweet or Savory)", // Eastern European
  "Pelmeni (Fried)", // Russian
  "Beef Stroganoff", // Russian
  "Samosas (Vegetable)", // Indian
  "Idli Sambar (Lentil Stew)", // Indian
  "Vada Sambar (Lentil Stew)", // Indian
  "Butter Naan", // Indian
  "Chicken Tikka Masala (Spicy)", // Indian
  "Rogan Josh (Lamb Curry)", // Indian
  "Biryani (Vegetable)", // Indian
  "Nigiri (Salmon)", // Japanese
  "Nigiri (Tuna)", // Japanese
  "Miso Soup", // Japanese
  "Yakitori (Chicken)", // Japanese
  "Takoyaki (Octopus Balls)", // Japanese
  "Dalgona Coffee (Cold)", // Korean
  "Bulgogi Kimchi Stew", // Korean
  "Sundubu Jjigae (Spicy Tofu Stew)", // Korean
  "Japchae (Glass Noodles)", // Korean
  "Jajangmyeon (Black Bean Noodles)", // Korean
  "Kimchi Fried Rice (With Spam)", // Korean
  "spicy korean sandwhich",
]
