
export const foodItems = [
  "Spaghetti",
  "Fried fish",
  "Lasagna",
  "Kefir",
  "Yogurt salad",
  "Chicken curry",
  "Hamburger",
  "Pizza Margherita",
  "Stir-fry",
  "Chocolate chip cookies",
  "Roast chicken",
  "Pasta carbonara",
  "Tacos",
  "Sushi",
  "Shepherd's pie",
  "Beef stew",
  "Caesar salad",
  "Fish and chips",
  "Bangers and mash",
  "Corned beef and cabbage",
  "Beef Wellington",
  "Bread pudding",
  "Cottage pie",
  "Eggplant Parmesan",
  "Chicken Parmesan",
  "Veal Parmesan",
  "Beef stroganoff",
  "Chicken piccata",
  "Pork tenderloin",
  "Beef brisket",
  "Pulled pork",
  "Beef bourguignon",
  "Chicken tikka masala",
  "Butter chicken",
  "Tandoori chicken",
  "Pad Thai",
  "Massaman curry",
  "Tom yum soup",
  "Kung Pao chicken",
  "Sweet and sour chicken",
  "Moo shu pork",
  "General Tso's chicken",
  "Beef and broccoli",
  "Szechuan beef",
  "Shrimp fried rice",
  "Vegetable fried rice",
  "Beef chow mein",
  "Chicken chow mein",
  "Shrimp lo mein",
  "Beef teriyaki",
  "Chicken teriyaki",
  "Salmon teriyaki",
  "Shrimp teriyaki",
  "Vegetable tempura",
  "Shrimp tempura",
  "Chicken katsu",
  "Tonkatsu",
  "Gyudon",
  "Sushi rolls",
  "California roll",
  "Philadelphia roll",
  "Spicy tuna roll",
  "Dragon roll",
  "Rainbow roll",
  "Cucumber roll",
  "Avocado roll",
  "Salmon roll",
  "Tuna roll",
  "Shrimp tempura roll",
  "Spider roll",
  "Eel roll",
  "Alaska roll",
  "Volcano roll",
  "Texas roll",
  "Bagel and lox",
  "Eggs Benedict",
  "Biscuits and gravy",
  "Chicken and waffles",
  "French toast",
  "Belgian waffles",
  "Pancakes",
  "Crepe",
  "Omelette",
  "Quiche",
  "Frittata",
  "Eggs Florentine",
  "Eggs Sardou",
  "Shakshuka",
  "Scrambled eggs",
  "Hard-boiled eggs",
  "Deviled eggs",
  "Egg salad",
  "Tuna salad",
  "Chicken salad",
  "Cobb salad",
  "Waldorf salad",
  "Greek salad",
  "Nicoise salad",
  "Caprese salad",
  "Fruit salad",
  "Coleslaw",
  "Macaroni salad",
  "Potato salad",
  "Pasta salad",
  "Ambrosia salad",
  "Broccoli salad",
  "Spinach salad",
  "Wedge salad",
  "Antipasto salad",
  "Chef salad",
  "House salad",
  "Guacamole",
  "Mashed potatoes",
  "French fries",
  "Grilled cheese sandwich",
  "Tomato soup",
  "Apple pie",
  "Banana bread",
  "Cheeseburger",
  "Meatloaf",
  "Risotto",
  "Fajitas",
  "Beef tacos",
  "Chicken parmesan",
  "Beef stir-fry",
  "Vegetable stir-fry",
  "Beef burritos",
  "Cesar salad",
  "Chicken soup",
  "Clam chowder",
  "Minestrone soup",
  "French onion soup",
  "Lentil soup",
  "Potato soup",
  "Split pea soup",
  "Chili con carne",
  "Vegetable curry",
  "Beef curry",
  "Vegetable lasagna",
  "Cheese pizza",
  "Pepperoni pizza",
  "Vegetable pizza",
  "BBQ chicken pizza",
  "Margherita pizza",
  "Calzone",
  "Hawaiian pizza",
  "Meat lovers pizza",
  "Seafood pizza",
  "Pesto pasta",
  "Alfredo pasta",
  "Macaroni and cheese",
  "Linguine with clam sauce",
  "Carbonara pasta",
  "Shrimp scampi",
  "Spaghetti aglio e olio",
  "Fettuccine alfredo",
  "Chicken Alfredo",
  "Tiramisu",
  "Chocolate cake",
  "Cheesecake",
  "Brownies",
  "Ice cream",
  "Apple crisp",
  "Key lime pie",
  "Pumpkin pie",
  "Blueberry muffins",
  "Cornbread",
  "Ratatouille",
  "Bolognese sauce",
  "Bechamel sauce",
  "Hollandaise sauce",
  "Marinara sauce",
  "Pesto sauce",
  "Salsa",
  "Hummus",
  "Pesto",
  "Tapenade",
  "Bruschetta",
  "Antipasto",
  "Nachos",
  "Stuffed peppers",
  "Eggplant parmesan",
  "Chicken fajitas",
  "Fish tacos",
  "Teriyaki chicken",
  "Miso soup",
  "Tempura",
  "Ceviche",
  "Gazpacho",
  "Quiche Lorraine",
  "Steak Diane",
  "Lobster bisque",
  "Crab cakes",
  "Escargot",
  "Bouillabaisse",
  "Coq au vin",
  "Croque monsieur",
  "Crepes Suzette",
  "Moussaka",
  "Baba ganoush",
  "Tabbouleh",
  "Falafel",
  "Shawarma",
  "Baklava",
  "Spanakopita",
  "Dolma",
  "Gyoza",
  "Ramen",
  "Pho",
  "Pad see ew",
  "Banh mi",
  "Bibimbap",
  "Kimchi",
  "Bulgogi",
  "Dumplings",
  "Samosa",
  "Naan",
  "Tikka masala",
  "Palak paneer",
  "Chana masala",
  "Biryani",
  "Dosa",
  "Idli",
  "Vada",
  "Tandoori naan",
  "Malai kofta",
  "Paneer tikka",
  "Aloo gobi",
  "Raita",
  "Pakora",
  "Jalebi",
  "Chole bhature",
  "Pani puri",
  "Samosa chaat",
  "Aloo tikki",
  "Matar paneer",
  "Bhindi masala",
  "Korma",
  "Kofta curry",
  "Aloo paratha",
  "Chapati",
  "Puri",
  "Upma",
  "Medu vada",
  "Rava dosa",
  "Hyderabadi biryani",
  "Chicken biryani",
  "Goan fish curry",
  "Vindaloo",
  "Mulligatawny soup",
  "Sheer khurma",
  "Halwa",
  "Rasmalai",
  "Gulab jamun",
  "Rasgulla",
  "Ladoo",
  "Kheer",
  "Barfi",
  "Shrikhand",
  "Pav bhaji",
  "Vada pav",
  "Dabeli",
  "Misal pav",
  "Poha",
  "Thalipeeth",
  "Sabudana khichdi",
  "Puran poli",
  "Modak",
  "Dhokla",
  "Khandvi",
  "Khaman",
  "Undhiyu",
  "Handvo",
  "Gujarati kadhi",
  "Thepla",
  "Methi na gota",
  "Chakri",
  "Khakhra",
  "Ghughra",
  "Fafda",
  "Kachori",
  "Gathiya",
  "Sev",
  "Kachumber",
  "Aloo chaat",
  "Papdi chaat",
  "Bhel puri",
  "Dahi puri",
  "Panipuri",
  "Ragda pattice",
  "Sev puri",
  "Katori chaat",
  "Tuna sandwich",
  "Club sandwich",
  "Turkey sandwich",
  "BLT sandwich",
  "Grilled chicken sandwich",
  "Roast beef sandwich",
  "Pulled pork sandwich",
  "Ham and cheese sandwich",
  "Reuben sandwich",
  "Monte Cristo sandwich",
  "Chicken Caesar salad",
  "Chef's salad",
  "Mozzarella sticks",
  "Onion rings",
  "Fried calamari",
  "Buffalo wings",
  "Chicken tenders",
  "Cheese fries",
  "Potato skins",
  "Garlic bread",
  "Stuffed mushrooms",
  "Chicken wings",
  "Quesadillas",
  "Spinach dip",
  "Fried pickles",
  "Cheese platter",
  "Crudites",
  "Fruit platter",
  "Charcuterie board",
  "Bacon cheeseburger",
  "Double cheeseburger",
  "Veggie burger",
  "Turkey burger",
  "BBQ burger",
  "Mushroom Swiss burger",
  "California burger",
  "Pulled pork burger",
  "Fish burger",
  "Tuna melt sandwich",
  "Philly cheesesteak",
  "French dip sandwich",
  "Meatball sub",
  "Grilled ham and cheese",
  "Sloppy joe sandwich",
  "Cuban sandwich",
  "Bahn mi sandwich",
  "Turkey club sandwich",
  "Ham and Swiss sandwich",
  "Pastrami sandwich",
  "Roast beef and cheddar sandwich",
  "Chicken parm sandwich",
  "Buffalo chicken sandwich",
  "BBQ pulled pork sandwich",
  "Egg salad sandwich",
  "Turkey cranberry sandwich",
  "Peanut butter and jelly sandwich",
  "Grilled peanut butter and banana sandwich",
  "Grilled chicken wrap",
  "Caesar chicken wrap",
  "Buffalo chicken wrap",
  "Crispy chicken wrap",
  "BLT wrap",
  "Turkey club wrap",
  "Veggie wrap",
  "Greek chicken wrap",
  "Hummus and veggie wrap",
  "Tuna salad wrap",
  "Grilled vegetable wrap",
  "Chicken Caesar wrap",
  "Southwest chicken wrap",
  "Cobb salad wrap",
  "Buffalo chicken salad wrap",
  "Chicken fajita wrap",
  "California turkey wrap",
  "Turkey cranberry wrap",
  "Chicken gyro",
  "Beef kebab",
  "Lamb tagine",
  "Salmon en papillote",
  "Lobster mac and cheese",
  "Mushroom risotto",
  "Avocado toast",
  "Tofu stir-fry",
  "Black bean quesadillas",
  "Spinach and feta stuffed chicken breast",
  "Shrimp scampi pasta",
  "Teriyaki salmon",
  "Cauliflower pizza crust",
  "Greek yogurt parfait",
  "Zucchini noodles with pesto",
  "Quinoa salad with roasted vegetables",
  "Caprese salad skewers",
  "Spinach and ricotta stuffed shells",
  "BBQ pulled jackfruit sandwich",
  "Coconut curry tofu",
  "Soba noodle salad",
  "Falafel wrap",
  "Veggie sushi rolls",
  "Lentil shepherd's pie",
  "Stuffed portobello mushrooms",
  "Buffalo cauliflower bites",
  "Thai green curry",
  "Spinach and artichoke stuffed mushrooms",
  "Teriyaki tofu bowls",
  "Quinoa stuffed bell peppers",
  "Mushroom barley soup",
  "Eggplant roll-ups",
  "Black bean burgers",
  "Stuffed acorn squash",
  "Lentil walnut loaf",
  "Veggie stir-fry with cashews",
  "Sweet potato black bean enchiladas",
  "Cauliflower rice pilaf",
  "Chickpea curry",
  "Pumpkin gnocchi",
  "Roasted vegetable frittata",
  "Beet and goat cheese salad",
  "Coconut lentil curry",
  "Cucumber avocado gazpacho",
  "Quinoa tabbouleh salad",
  "Stuffed grape leaves",
  "Roasted Brussels sprouts with balsamic glaze",
  "Mushroom Wellington",
  "Ratatouille tart",
  "Cauliflower buffalo wings",
  "Lentil sloppy joes",
  "Zucchini boats filled with quinoa",
  "Black bean and corn salad",
  "Greek lentil salad",
  "Spinach and ricotta stuffed portobello mushrooms",
  "Avocado chickpea salad",
  "Tofu scramble",
  "Eggplant caprese stacks",
  "Mediterranean quinoa salad",
  "Sweet potato toast",
  "Cauliflower alfredo",
  "Quinoa stuffed zucchini",
  "Chickpea avocado wrap",
  "Tempeh stir-fry",
  "Butternut squash risotto",
  "Eggplant parmesan stacks",
  "Tofu banh mi",
  "Mushroom lentil meatballs",
  "Coconut curry lentils",
  "Portobello mushroom steaks",
  "Avocado cucumber sushi",
  "Lentil walnut tacos",
  "Veggie spring rolls",
  "Roasted vegetable couscous",
  "Quinoa avocado salad",
  "Stuffed sweet potatoes",
  "Black bean corn enchiladas",
  "Teriyaki tempeh bowls",
  "Cauliflower tikka masala",
  "Spinach and feta stuffed peppers",
  "Chickpea spinach curry",
  "Zucchini noodle pad Thai",
  "Buffalo cauliflower salad",
  "Sesame tofu stir-fry",
  "Stuffed bell pepper soup",
  "Mediterranean stuffed eggplant",
  "Cauliflower potato mash",
  "Vegan sushi burrito",
  "Quinoa black bean chili",
  "Sweet potato black bean tacos",
  "Lentil spinach curry",
  "Mushroom lentil shepherd's pie",
  "Eggplant parmesan pasta",
  "Tofu tikka masala",
  "Cauliflower chickpea curry",
  "Veggie stir-fry with peanut sauce",
  "Lentil mushroom bolognese",
  "Spaghetti squash primavera",
  "Vegan mac and cheese",
  "Roasted vegetable quinoa bowl",
  "Chickpea avocado salad",
  "Sweet potato chickpea curry",
  "Stuffed acorn squash with quinoa",
  "Cauliflower buffalo wraps",
  "Vegan shepherd's pie",
  "Portobello mushroom burgers with avocado",
  "Quinoa black bean burgers",
  "Tofu vegetable stir-fry",
  "Veggie sushi bowl",
  "Coconut curry vegetables",
  "Stuffed portobello mushrooms with quinoa",
  "Sweet potato black bean burritos",
  "Lentil vegetable curry",
  "Mushroom lentil loaf",
  "Vegan stuffed peppers",
  "Cauliflower rice stir-fry",
  "Tofu noodle soup",
  "Vegan taco salad",
  "Chickpea avocado wraps",
  "Sweet potato chickpea stew",
  "Stuffed butternut squash",
  "Cauliflower rice sushi",
  "Vegan lentil soup",
  "Portobello mushroom fajitas",
  "Quinoa avocado bowls",
  "Tofu lettuce wraps",
  "Veggie quinoa stir-fry",
  "Coconut curry noodles",
  "Stuffed cabbage rolls",
  "Sweet potato black bean chili",
  "Lentil curry soup",
  "Mushroom walnut burgers",
  "Vegan paella",
  "Cauliflower rice burrito bowls",
  "Tofu vegetable curry",
  "Veggie sushi rolls with avocado",
  "Coconut curry lentil soup",
  "Stuffed spaghetti squash boats",
  "Vegan stuffed mushrooms",
  "Cauliflower rice sushi rolls",
  "Tofu pad Thai",
  "Veggie stir-fry with tofu",
  "Coconut curry chickpeas",
  "Stuffed bell peppers with quinoa",
  "Cauliflower pizza with vegan cheese",
]
