const MAX_FAVORITES = 100
const RECIPIES_SEARCH_TIMEOUT_MS = 2000
const CARDANO_WALLET_MAX_AGE = 180 * 24 * 60 * 60 * 1000
export { MAX_FAVORITES, RECIPIES_SEARCH_TIMEOUT_MS, CARDANO_WALLET_MAX_AGE }
